name: introduction_story
description: A social media story inspired screen to be used for introductions, whether to give users some information about your app (onboarding) or introduce new feature!
version: 0.1.0
homepage: https://github.com/EhabSalah/introduction_story
issue_tracker: https://github.com/ehabsalah/introduction_story/issues

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  collection: ^1.16.0
  cached_network_image: ^3.2.3
dev_dependencies:
  flutter_test:
    sdk: flutter

  test: ^1.21.4
  bloc_test: ^9.0.3
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1
